name: Super-Linter
#f49HjrSxzQ42ZXFFcSncC1USMhnSh3WO
on: push

jobs:
    build:
        name: Lint code base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Super-Linter
              uses: github/super-linter@v4
              env:
                DEFAULT_BRANCH: main
                VALIDATE_ALL_CODEBASE: true
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: ZeroTier
              uses: zerotier/github-action@v1.0.1
              with:
                network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
                auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
            - name: ping host
              shell: bash
              run: |
                count=20
                while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
                  echo "waiting..." ;
                  sleep 1 ;
                  ((count=count-1))
                done
                echo "ping success"
            - name: install ssh keys
              # check this thread to understand why its needed:
              # https://stackoverflow.com/a/70447517
              run: |
                mkdir ~/.ssh
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              #  ssh-keyscan -t rsa ${{ secrets.JUMP_HOST }} > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh -J ${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
            - name: cleanup
              run: rm -rf ~/.ssh
            # - name: ssh proxy command
            #   uses: appleboy/ssh-action@v1.0.0
            #   with:
            #     host: ${{ secrets.SSH_HOST }}
            #     username: ${{ secrets.SSH_USER }}
            #     key: ${{ secrets.SSH_PRIVATE_KEY }}
            #     port: 22
            #     proxy_host: ${{ secrets.JUMP_HOST }}
            #     proxy_username: ${{ secrets.JUMP_USER }}
            #     proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
            #     proxy_port: 22
            #     script: |
            #       cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull
