name: Super-Linter
on: push
jobs:
    build:
        name: Lint code base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Super-Linter
              uses: github/super-linter@v4
              env:
                DEFAULT_BRANCH: main
                VALIDATE_ALL_CODEBASE: true
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: ZeroTier
              uses: zerotier/github-action@v1.0.1
              with:
                network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
                auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
            - name: ping host
              shell: bash
              run: |
                count=20
                while ! ping -c 1 ${{ secrets.ZEROTIER_HOST_IP }} ; do
                  echo "waiting..." ;
                  sleep 1 ;
                  ((count=count-1))
                done
                echo "ping success"
            - name: install ssh keys
              run: |
                mkdir ~/.ssh
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                echo "${{ secrets.SSH_KNOW_HOST }}" > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh -J ${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
            - name: cleanup
              run: rm -rf ~/.ssh
